server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecommerce}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
    jackson:
      serialization:
        # Tarihleri "2026, 3, 19..." gibi bir sayı dizisi yerine düzgün bir metin olarak yazması için
        write-dates-as-timestamps: false

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    # Sadece kendi yazdığın logları görmek için:
    com.ecommerce.product: INFO